/* Reason-based short courses. Each track is 4 units of about 15 minutes. nl phrase: [text, meaning]. ja phrase: [text, reading, romaji, meaning]. */
const TRACKS_META = [
  { id:"trip", title:"Trip-ready", sub:"One hour before your trip", cert:"Trip-ready" },
  { id:"life", title:"Daily life and community", sub:"Neighbours, errands, friends, starting a group", cert:"Community-ready" },
  { id:"student", title:"Student life", sub:"Campus, class, housing, part-time work", cert:"Campus-ready" },
  { id:"tech", title:"Tech at work", sub:"First day, stand-ups, reviews, office life", cert:"Work-ready" }
];
const TRACKS = {
nl: {
  trip:[
    { title:"Hello and polite basics", tip:"Dutch people switch to English fast. Starting in Dutch still gets you a smile.", p:[["Hallo!","Hello!"],["Dank je wel.","Thank you."],["Sorry, ik spreek geen Nederlands.","Sorry, I don't speak Dutch."],["Spreekt u Engels?","Do you speak English?"],["Pardon, mag ik even langs?","Excuse me, can I get past?"]] },
    { title:"Getting around", tip:"Check in and out with your card on every train, tram and bus.", p:[["Waar is het station?","Where is the station?"],["Een kaartje naar Amsterdam, alstublieft.","A ticket to Amsterdam, please."],["Welk perron?","Which platform?"],["Is dit de trein naar Utrecht?","Is this the train to Utrecht?"],["Waar kan ik een fiets huren?","Where can I rent a bike?"]] },
    { title:"Food and shopping", tip:"Many places are card-only, and you usually ask for the bill yourself.", p:[["Een tafel voor twee, alstublieft.","A table for two, please."],["Mag ik de kaart?","Can I have the menu?"],["Ik ben vegetariër.","I'm vegetarian."],["Mag ik afrekenen?","Can I pay, please?"],["Kan ik met kaart betalen?","Can I pay by card?"]] },
    { title:"Help and safety", tip:"Emergency number in the Netherlands: 112.", p:[["Kunt u mij helpen?","Can you help me?"],["Ik ben verdwaald.","I'm lost."],["Waar is de wc?","Where is the toilet?"],["Laat me met rust.","Leave me alone."],["Bel 112, alstublieft!","Call 112, please!"]] }
  ],
  life:[
    { title:"Meeting neighbours", tip:"Say hi when you move in. Neighbours are often your first friends.", p:[["Hoi, ik ben je nieuwe buurvrouw.","Hi, I'm your new neighbour."],["Ik woon hier sinds kort.","I've only lived here a short time."],["Waar kom jij vandaan?","Where are you from?"],["Leuk je te ontmoeten!","Nice to meet you!"],["Zullen we een keer koffie drinken?","Shall we have coffee sometime?"]] },
    { title:"Everyday errands", tip:"Your GP (huisarts) is the first stop for anything medical.", p:[["Nee, dank je, ik heb een tas.","No thanks, I have a bag."],["Ik zoek de melk.","I'm looking for the milk."],["Ik wil een afspraak maken bij de huisarts.","I'd like to make an appointment with the GP."],["Mijn kind is ziek.","My child is ill."],["Hoe laat gaat de school uit?","What time does school finish?"]] },
    { title:"Making friends", tip:"Ask people to keep speaking Dutch with you. It's the fastest way to learn.", p:[["Wat doe jij in het weekend?","What do you do at the weekend?"],["Ik ben nieuw hier en ik ken nog niet veel mensen.","I'm new here and I don't know many people yet."],["Heb je zin om mee te gaan?","Do you want to come along?"],["Mag ik je nummer?","Can I have your number?"],["Spreek langzaam, alsjeblieft. Ik oefen mijn Nederlands.","Please speak slowly. I'm practising my Dutch."]] },
    { title:"Starting a group", tip:"A weekly meetup at the library or a café is an easy start.", p:[["Ik organiseer een taalcafé.","I'm organising a language café."],["Iedereen is welkom.","Everyone is welcome."],["We komen elke zaterdag om tien uur samen.","We meet every Saturday at ten."],["Wil je je voorstellen?","Would you like to introduce yourself?"],["Bedankt voor het komen!","Thanks for coming!"]] }
  ],
  student:[
    { title:"On campus", tip:"Lectures are 'colleges' in Dutch, a classic false friend.", p:[["Waar is de collegezaal?","Where is the lecture hall?"],["Ik ben een internationale student.","I'm an international student."],["Wanneer begint het college?","When does the lecture start?"],["Waar is de bibliotheek?","Where is the library?"],["Ik zoek het studentenloket.","I'm looking for the student desk."]] },
    { title:"In class", tip:"Asking questions is normal and expected in Dutch classrooms.", p:[["Kunt u dat herhalen?","Can you repeat that?"],["Ik begrijp het niet helemaal.","I don't quite understand."],["Wat is de deadline?","What's the deadline?"],["Mag ik een vraag stellen?","May I ask a question?"],["Zullen we samen studeren?","Shall we study together?"]] },
    { title:"Housing", tip:"You need to register your address with the municipality (gemeente).", p:[["Ik zoek een kamer.","I'm looking for a room."],["Hoeveel is de huur per maand?","How much is the rent per month?"],["Zijn gas, water en licht inbegrepen?","Are utilities included?"],["Wanneer kan ik de kamer bekijken?","When can I view the room?"],["Ik moet me inschrijven bij de gemeente.","I have to register with the municipality."]] },
    { title:"Part-time job", tip:"Cafés and restaurants (horeca) hire a lot of students.", p:[["Ik zoek een bijbaan.","I'm looking for a part-time job."],["Ik kan in het weekend werken.","I can work at weekends."],["Hoeveel uur per week?","How many hours per week?"],["Ik heb ervaring in de horeca.","I have experience in hospitality."],["Wanneer kan ik beginnen?","When can I start?"]] }
  ],
  tech:[
    { title:"First day", tip:"Work culture is informal: first names, direct feedback.", p:[["Goedemorgen, ik ben de nieuwe engineer.","Good morning, I'm the new engineer."],["Ik werk in het platformteam.","I work in the platform team."],["Waar is mijn bureau?","Where is my desk?"],["Wie is mijn manager?","Who is my manager?"],["Ik spreek nog een beetje Nederlands.","I speak a little Dutch so far."]] },
    { title:"Stand-up and meetings", tip:"Short, direct updates are the norm.", p:[["Gisteren heb ik aan de migratie gewerkt.","Yesterday I worked on the migration."],["Vandaag ga ik de bug oplossen.","Today I'm going to fix the bug."],["Ik zit vast op dit probleem.","I'm stuck on this problem."],["Kunnen we dit na de meeting bespreken?","Can we discuss this after the meeting?"],["Zullen we verder in het Engels?","Shall we continue in English?"]] },
    { title:"Asking and helping", tip:"Disagreeing openly is fine, as long as you give a reason.", p:[["Heb je even tijd?","Do you have a moment?"],["Kun je naar mijn pull request kijken?","Can you look at my pull request?"],["Dat is een goed idee.","That's a good idea."],["Ik ben het er niet helemaal mee eens.","I don't fully agree."],["Ik laat het je vandaag nog weten.","I'll let you know today."]] },
    { title:"Office life", tip:"Lunch is often a quick sandwich together, around noon.", p:[["Wie gaat er mee lunchen?","Who's coming to lunch?"],["Ik werk morgen thuis.","I'm working from home tomorrow."],["Fijn weekend!","Have a nice weekend!"],["Proost!","Cheers!"],["Tot morgen!","See you tomorrow!"]] }
  ]
},
fr: {
  trip:[
    { title:"Hello and polite basics", tip:"Always say Bonjour when you walk into a shop. Skipping it comes across as rude.", p:[["Bonjour !","Hello! / Good morning!"],["Merci beaucoup.","Thank you very much."],["Désolé, je ne parle pas français.","Sorry, I don't speak French."],["Vous parlez anglais ?","Do you speak English?"],["Excusez-moi, je peux passer ?","Excuse me, can I get past?"]] },
    { title:"Getting around", tip:"Check the departure board for the platform (voie); it often appears only 20 minutes before.", p:[["Où est la gare ?","Where is the station?"],["Un billet pour Lyon, s'il vous plaît.","A ticket to Lyon, please."],["C'est quelle voie ?","Which platform is it?"],["Ce train va à Marseille ?","Does this train go to Marseille?"],["Où est l'arrêt de bus ?","Where is the bus stop?"]] },
    { title:"Food and shopping", tip:"Service is included in the bill. Ask for the bill: it won't come by itself.", p:[["Une table pour deux, s'il vous plaît.","A table for two, please."],["La carte, s'il vous plaît.","The menu, please."],["Je suis végétarien.","I'm vegetarian. (végétarienne for a woman)"],["L'addition, s'il vous plaît.","The bill, please."],["Je peux payer par carte ?","Can I pay by card?"]] },
    { title:"Help and safety", tip:"Emergency: 112. Ambulance (SAMU): 15. Police: 17. Fire: 18.", p:[["Vous pouvez m'aider ?","Can you help me?"],["Je suis perdu.","I'm lost. (perdue for a woman)"],["Où sont les toilettes ?","Where are the toilets?"],["Laissez-moi tranquille.","Leave me alone."],["Appelez la police !","Call the police!"]] }
  ],
  life:[
    { title:"Meeting neighbours", tip:"Use vous with new neighbours until they suggest tu.", p:[["Bonjour, je suis votre nouvelle voisine.","Hello, I'm your new neighbour. (nouveau voisin for a man)"],["J'habite ici depuis peu.","I've only lived here a short time."],["Vous venez d'où ?","Where are you from?"],["Enchantée !","Nice to meet you! (enchanté for a man)"],["On prend un café un de ces jours ?","Shall we have coffee one of these days?"]] },
    { title:"Everyday errands", tip:"Register a médecin traitant (your regular GP): it's your first stop for health.", p:[["Non merci, j'ai un sac.","No thanks, I have a bag."],["Je cherche le lait.","I'm looking for the milk."],["Je voudrais prendre rendez-vous chez le médecin.","I'd like to make a doctor's appointment."],["Mon enfant est malade.","My child is ill."],["L'école finit à quelle heure ?","What time does school finish?"]] },
    { title:"Making friends", tip:"Clubs and associations are the easiest way to meet people in France.", p:[["Qu'est-ce que tu fais le week-end ?","What do you do at the weekend?"],["Je suis nouvelle ici et je ne connais pas encore beaucoup de monde.","I'm new here and I don't know many people yet. (nouveau for a man)"],["Tu veux venir avec nous ?","Do you want to come with us?"],["Je peux avoir ton numéro ?","Can I have your number?"],["Parle lentement, s'il te plaît. J'apprends le français.","Please speak slowly. I'm learning French."]] },
    { title:"Starting a group", tip:"Libraries and community centres (maisons de quartier) often host groups for free.", p:[["J'organise un café des langues.","I'm organising a language café."],["Tout le monde est bienvenu.","Everyone is welcome."],["On se retrouve tous les samedis à dix heures.","We meet every Saturday at ten."],["Tu veux te présenter ?","Would you like to introduce yourself?"],["Merci d'être venus !","Thanks for coming!"]] }
  ],
  student:[
    { title:"On campus", tip:"The CROUS runs student housing, cafeterias and grants.", p:[["Où est l'amphithéâtre ?","Where is the lecture hall?"],["Je suis étudiante internationale.","I'm an international student. (étudiant for a man)"],["Le cours commence à quelle heure ?","What time does the class start?"],["Où est la bibliothèque ?","Where is the library?"],["Je cherche le secrétariat.","I'm looking for the admin office."]] },
    { title:"In class", tip:"Asking after class is normal. Professors often have office hours.", p:[["Vous pouvez répéter, s'il vous plaît ?","Could you repeat that, please?"],["Je n'ai pas bien compris.","I didn't quite understand."],["C'est pour quand ?","When is it due?"],["Je peux poser une question ?","May I ask a question?"],["On révise ensemble ?","Shall we study together?"]] },
    { title:"Housing", tip:"Landlords often ask for a guarantor (garant). Students can use the free Visale guarantee.", p:[["Je cherche une chambre.","I'm looking for a room."],["Le loyer est de combien par mois ?","How much is the rent per month?"],["Les charges sont comprises ?","Are utilities included?"],["Je peux visiter quand ?","When can I visit?"],["Il me faut un garant ?","Do I need a guarantor?"]] },
    { title:"Part-time job", tip:"International students can work up to 964 hours a year.", p:[["Je cherche un petit boulot.","I'm looking for a part-time job."],["Je peux travailler le week-end.","I can work at weekends."],["C'est combien d'heures par semaine ?","How many hours a week is it?"],["J'ai de l'expérience en restauration.","I have experience working in restaurants."],["Je peux commencer quand ?","When can I start?"]] }
  ],
  tech:[
    { title:"First day", tip:"Tech teams often use tu. Follow what your colleagues do.", p:[["Bonjour, je suis la nouvelle ingénieure.","Hello, I'm the new engineer. (le nouvel ingénieur for a man)"],["Je travaille dans l'équipe plateforme.","I work in the platform team."],["Où est mon bureau ?","Where is my desk?"],["Qui est mon manager ?","Who is my manager?"],["Je ne parle qu'un peu français pour l'instant.","I only speak a little French for now."]] },
    { title:"Stand-up and meetings", tip:"Meetings often start with a few minutes of small talk.", p:[["Hier, j'ai travaillé sur la migration.","Yesterday I worked on the migration."],["Aujourd'hui, je vais corriger le bug.","Today I'm going to fix the bug."],["Je suis bloquée sur ce problème.","I'm stuck on this problem. (bloqué for a man)"],["On peut en parler après la réunion ?","Can we talk about it after the meeting?"],["On continue en anglais ?","Shall we continue in English?"]] },
    { title:"Asking and helping", tip:"Polite requests use the conditional: tu pourrais, vous pourriez.", p:[["Tu as une minute ?","Do you have a minute?"],["Tu pourrais relire ma pull request ?","Could you review my pull request?"],["C'est une bonne idée.","That's a good idea."],["Je ne suis pas tout à fait d'accord.","I don't fully agree."],["Je te redis ça aujourd'hui.","I'll get back to you on that today."]] },
    { title:"Office life", tip:"Lunch is a real break in France, often a full hour.", p:[["Qui vient déjeuner ?","Who's coming to lunch?"],["Demain, je suis en télétravail.","I'm working from home tomorrow."],["Bon week-end !","Have a good weekend!"],["Santé !","Cheers!"],["À demain !","See you tomorrow!"]] }
  ]
},
ja: {
  trip:[
    { title:"Hello and polite basics", tip:"すみません works for 'excuse me', 'sorry' and getting a waiter's attention.", p:[["こんにちは。","こんにちは","konnichiwa","Hello."],["ありがとうございます。","ありがとうございます","arigatou gozaimasu","Thank you."],["すみません。","すみません","sumimasen","Excuse me. / Sorry."],["英語は話せますか。","えいごははなせますか","eigo wa hanasemasu ka","Do you speak English?"],["日本語がわかりません。","にほんごがわかりません","nihongo ga wakarimasen","I don't understand Japanese."]] },
    { title:"Getting around", tip:"Show the name of your stop on your phone and ask: ここまでお願いします.", p:[["駅はどこですか。","えきはどこですか","eki wa doko desu ka","Where is the station?"],["この電車は新宿に行きますか。","このでんしゃはしんじゅくにいきますか","kono densha wa shinjuku ni ikimasu ka","Does this train go to Shinjuku?"],["何番線ですか。","なんばんせんですか","nanbansen desu ka","Which platform?"],["切符はどこで買えますか。","きっぷはどこでかえますか","kippu wa doko de kaemasu ka","Where can I buy a ticket?"],["ここまでお願いします。","ここまでおねがいします","koko made onegai shimasu","To here, please."]] },
    { title:"Food and shopping", tip:"No tipping in Japan. Pay at the register on your way out.", p:[["二人です。","ふたりです","futari desu","Two people."],["これをください。","これをください","kore o kudasai","This one, please."],["肉なしでお願いします。","にくなしでおねがいします","niku nashi de onegai shimasu","Without meat, please."],["カードで払えますか。","カードではらえますか","kaado de haraemasu ka","Can I pay by card?"],["お会計お願いします。","おかいけいおねがいします","okaikei onegai shimasu","The bill, please."]] },
    { title:"Help and safety", tip:"Police: 110. Ambulance and fire: 119. Koban (police boxes) help with directions too.", p:[["助けてください。","たすけてください","tasukete kudasai","Please help me."],["道に迷いました。","みちにまよいました","michi ni mayoimashita","I'm lost."],["トイレはどこですか。","トイレはどこですか","toire wa doko desu ka","Where is the toilet?"],["やめてください。","やめてください","yamete kudasai","Please stop."],["警察を呼んでください。","けいさつをよんでください","keisatsu o yonde kudasai","Please call the police."]] }
  ],
  life:[
    { title:"Meeting neighbours", tip:"A small gift when you move in is a common way to say hello.", p:[["はじめまして。","はじめまして","hajimemashite","Nice to meet you."],["隣に引っ越してきました。","となりにひっこしてきました","tonari ni hikkoshite kimashita","I've just moved in next door."],["インドから来ました。","インドからきました","indo kara kimashita","I'm from India. (Say your own country.)"],["どちらから来ましたか。","どちらからきましたか","dochira kara kimashita ka","Where are you from?"],["よろしくお願いします。","よろしくおねがいします","yoroshiku onegai shimasu","I look forward to getting to know you."]] },
    { title:"Everyday errands", tip:"Garbage days and sorting rules are set by your ward. Ask a neighbour.", p:[["ゴミの日はいつですか。","ごみのひはいつですか","gomi no hi wa itsu desu ka","Which day is garbage day?"],["袋はいりません。","ふくろはいりません","fukuro wa irimasen","I don't need a bag."],["病院の予約をしたいです。","びょういんのよやくをしたいです","byouin no yoyaku o shitai desu","I'd like to book a doctor's appointment."],["子どもが熱を出しました。","こどもがねつをだしました","kodomo ga netsu o dashimashita","My child has a fever."],["保育園の申し込みはどこですか。","ほいくえんのもうしこみはどこですか","hoikuen no moushikomi wa doko desu ka","Where do I apply for daycare?"]] },
    { title:"Making friends", tip:"LINE is how most people keep in touch in Japan.", p:[["週末は何をしていますか。","しゅうまつはなにをしていますか","shuumatsu wa nani o shite imasu ka","What do you do at weekends?"],["一緒にお茶しませんか。","いっしょにおちゃしませんか","issho ni ocha shimasen ka","Shall we get tea together?"],["LINEを交換しませんか。","ラインをこうかんしませんか","rain o koukan shimasen ka","Shall we swap LINE?"],["日本語を勉強中です。","にほんごをべんきょうちゅうです","nihongo o benkyouchuu desu","I'm studying Japanese."],["ゆっくり話してください。","ゆっくりはなしてください","yukkuri hanashite kudasai","Please speak slowly."]] },
    { title:"Starting a group", tip:"Community centres (公民館) rent rooms cheaply for local groups.", p:[["言語交換の会をしています。","げんごこうかんのかいをしています","gengo koukan no kai o shite imasu","I run a language exchange group."],["誰でも参加できます。","だれでもさんかできます","dare demo sanka dekimasu","Anyone can join."],["毎週土曜日の十時に集まります。","まいしゅうどようびのじゅうじにあつまります","maishuu doyoubi no juuji ni atsumarimasu","We meet every Saturday at ten."],["自己紹介をお願いします。","じこしょうかいをおねがいします","jikoshoukai o onegai shimasu","Please introduce yourself."],["来てくれてありがとう。","きてくれてありがとう","kite kurete arigatou","Thanks for coming."]] }
  ],
  student:[
    { title:"On campus", tip:"Carry your student ID. You need it for the library and discounts.", p:[["留学生です。","りゅうがくせいです","ryuugakusei desu","I'm an international student."],["教室はどこですか。","きょうしつはどこですか","kyoushitsu wa doko desu ka","Where is the classroom?"],["図書館は何時まで開いていますか。","としょかんはなんじまであいていますか","toshokan wa nanji made aite imasu ka","Until what time is the library open?"],["学生証を忘れました。","がくせいしょうをわすれました","gakuseishou o wasuremashita","I forgot my student ID."],["事務室はどこですか。","じむしつはどこですか","jimushitsu wa doko desu ka","Where is the office?"]] },
    { title:"In class", tip:"If you didn't catch something, もう一度お願いします is always polite.", p:[["もう一度お願いします。","もういちどおねがいします","mou ichido onegai shimasu","Once more, please."],["よくわかりませんでした。","よくわかりませんでした","yoku wakarimasen deshita","I didn't quite understand."],["締め切りはいつですか。","しめきりはいつですか","shimekiri wa itsu desu ka","When is the deadline?"],["質問してもいいですか。","しつもんしてもいいですか","shitsumon shite mo ii desu ka","May I ask a question?"],["一緒に勉強しませんか。","いっしょにべんきょうしませんか","issho ni benkyou shimasen ka","Shall we study together?"]] },
    { title:"Housing", tip:"Many rentals charge a deposit (敷金) and key money (礼金) up front.", p:[["部屋を探しています。","へやをさがしています","heya o sagashite imasu","I'm looking for a room."],["家賃はいくらですか。","やちんはいくらですか","yachin wa ikura desu ka","How much is the rent?"],["敷金と礼金はありますか。","しききんとれいきんはありますか","shikikin to reikin wa arimasu ka","Is there a deposit and key money?"],["駅から歩いて何分ですか。","えきからあるいてなんぷんですか","eki kara aruite nanpun desu ka","How many minutes' walk from the station?"],["区役所で住所を登録しました。","くやくしょでじゅうしょをとうろくしました","kuyakusho de juusho o touroku shimashita","I registered my address at the ward office."]] },
    { title:"Part-time job", tip:"On a student visa you need permission to work, usually up to 28 hours a week during term.", p:[["アルバイトを探しています。","アルバイトをさがしています","arubaito o sagashite imasu","I'm looking for a part-time job."],["週に二十八時間まで働けます。","しゅうににじゅうはちじかんまではたらけます","shuu ni nijuuhachi jikan made hatarakemasu","I can work up to 28 hours a week."],["土日も働けます。","どにちもはたらけます","donichi mo hatarakemasu","I can work weekends too."],["面接はいつですか。","めんせつはいつですか","mensetsu wa itsu desu ka","When is the interview?"],["いつから始められますか。","いつからはじめられますか","itsu kara hajimeraremasu ka","From when can I start?"]] }
  ],
  tech:[
    { title:"First day", tip:"Formal set phrases matter more than grammar on day one.", p:[["本日からお世話になります。","ほんじつからおせわになります","honjitsu kara osewa ni narimasu","I'm joining from today. Thank you in advance."],["プラットフォームチームのエンジニアです。","プラットフォームチームのエンジニアです","purattofoomu chiimu no enjinia desu","I'm an engineer on the platform team."],["日本語はまだ勉強中です。","にほんごはまだべんきょうちゅうです","nihongo wa mada benkyouchuu desu","I'm still learning Japanese."],["よろしくお願いいたします。","よろしくおねがいいたします","yoroshiku onegai itashimasu","I look forward to working with you."],["お先に失礼します。","おさきにしつれいします","osaki ni shitsurei shimasu","Excuse me for leaving before you."]] },
    { title:"Stand-up and meetings", tip:"相談 (consulting early) is valued. Raise problems before they grow.", p:[["昨日はマイグレーションの作業をしました。","きのうはマイグレーションのさぎょうをしました","kinou wa maigureeshon no sagyou o shimashita","Yesterday I worked on the migration."],["今日はバグを修正します。","きょうはバグをしゅうせいします","kyou wa bagu o shuusei shimasu","Today I'll fix the bug."],["この問題で詰まっています。","このもんだいでつまっています","kono mondai de tsumatte imasu","I'm stuck on this issue."],["会議の後で相談させてください。","かいぎのあとでそうだんさせてください","kaigi no ato de soudan sasete kudasai","Let me talk it through with you after the meeting."],["英語で話してもいいですか。","えいごではなしてもいいですか","eigo de hanashite mo ii desu ka","Is it OK if I speak in English?"]] },
    { title:"Asking and helping", tip:"承知しました is the safe, polite 'got it' with managers and clients.", p:[["今、少しよろしいですか。","いま、すこしよろしいですか","ima, sukoshi yoroshii desu ka","Do you have a moment now?"],["プルリクエストのレビューをお願いできますか。","プルリクエストのレビューをおねがいできますか","puru rikuesuto no rebyuu o onegai dekimasu ka","Could you review my pull request?"],["確認します。","かくにんします","kakunin shimasu","I'll check."],["承知しました。","しょうちしました","shouchi shimashita","Understood."],["今日中にご連絡します。","きょうじゅうにごれんらくします","kyoujuu ni gorenraku shimasu","I'll get back to you today."]] },
    { title:"Office life", tip:"お疲れさまです works as hello, goodbye and thanks at work.", p:[["お疲れさまです。","おつかれさまです","otsukaresama desu","Thanks for your hard work. (work greeting)"],["一緒にランチに行きませんか。","いっしょにランチにいきませんか","issho ni ranchi ni ikimasen ka","Shall we go for lunch?"],["明日は在宅勤務です。","あしたはざいたくきんむです","ashita wa zaitaku kinmu desu","I'm working from home tomorrow."],["乾杯！","かんぱい","kanpai","Cheers!"],["良い週末を。","よいしゅうまつを","yoi shuumatsu o","Have a good weekend."]] }
  ]
}
};
